### ISSUE TITLE
Multiple cars causes AttributeError

### ISSUE THREAD

**Issue by quinnsam** [sdague/mychevy#1]
* mychevy version: 0.2.0
* Python version: 2.7.5
* Operating System: CentOS 7 - Gnome

### Description

More than one car in the MyChevy web app causes "AttributeError"

### What I Did

I followed the exact startup procedure that is on the README. However just like you suspected when there is more than one car it did not work.

The taceback is posted below.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mychevy/mychevy.py", line 149, in data
    plugged_in, state = self.parse_plug(driver)
  File "/usr/lib/python2.7/site-packages/mychevy/mychevy.py", line 72, in parse_plug
    status = self._status_bary_right(driver)
AttributeError: 'MyChevy' object has no attribute '_status_bary_right'
```

I would love to help you get this working. I currently have 3 cars in the MyChevy app so if you need me to provide you with logs, files or anything I will. Thanks for your great work.

**Comment by sdague** [comment]
Yeh, this is not super surprising. There are a lot of ways this can go wrong for sure, and my process for developing this was pretty fragile and using Chrome inspector a lot.

Sometime next week I'll try to build a tool that will generate dumps along the way to see what the data ends up looking like. Maybe that can help me figure out the next steps here.

**Comment by sdague** [comment]
I have some test code up, can you try to pull the "json" branch of the git repo, pip install that, then run the mychevy-debug tool? 

See if that provides a list of 3 vehicles.

**Comment by sdague** [comment]
Please test with 0.3.0, I think this will work now.
