### ISSUE TITLE
Mileage related values have too much precision

### ISSUE THREAD

**Issue by austinmroczek** [sdague/mychevy#18]
* mychevy version: 2.1.1
* Python version: 3.9
* Operating System: Raspbian Buster

### Description

I'm using mychevy via Home Assistant version 2021.2.3.

It's working great except that the sensor returns a number with 9 decimal places for sensors measured in miles. 

To be in line with the myChevy website, and what my car actually shows, I'd recommend rounding it to the nearest whole mile. 

### What I Did

Open Home Assistant UI, look at mychevy sensors.

I submitted a PR for Home Assistant core that would round the numbers, but their team is recommending it be rounded by this library instead of Home Assistant needed to do it.  See https://github.com/home-assistant/core/pull/46879/

Willing to submit a PR here, but I don't know the code at all and would appreciate being pointed in the right direction.

**Comment by sdague** [comment]
Thanks for linking in the issue, it is coming from upstream. One way to solve this would be to make the numbers fields properties instead, and the ones that are floats get precision rounded when accessed.

**Comment by austinmroczek** [comment]
Thanks for the help
